In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [2]:
%qtconsole

In [3]:
# X = np.array([[20,8],[15,20],[16,10],[5,15],[16,6],[2,20]])
# W = np.random.rand(2,1)
# y = np.array([1,1,-1,-1,-1,-1])
X = np.array([1,-3,2])
W = np.array([0.5,-1,-1.5])
label = 2

In [4]:
print(X)

[ 1 -3  2]


In [5]:
with tf.GradientTape(persistent=True) as t:
    X = tf.constant([1., -3., 2.], shape=[1, 3])
    W = tf.constant([0.5, -1., -1.5], shape=[3, 1])
    label = tf.constant([2.0], shape=[1,1])
    t.watch(X)
    t.watch(W)
    y = tf.sigmoid(tf.matmul(X,W))
    error = tf.add(label,-y)
    L = tf.square(error)

    dL_dX = t.gradient(L, X)
    dL_dW = t.gradient(L,W)

In [6]:
tf.print(L)
tf.print(dL_dX)
tf.print(dL_dW)

[[1.89761806]]
[[-0.323727131 0.647454262 0.971181393]]
[[-0.647454262]
 [1.94236279]
 [-1.29490852]]


In [7]:
import tensorflow_datasets as tfds

In [8]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [9]:
from tensorflow import keras

In [10]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Flatten(input_shape=(28, 28)))
model.add(tf.keras.layers.Dense(120, activation='sigmoid'))
model.add(tf.keras.layers.Dense(80, activation='sigmoid'))
model.add(tf.keras.layers.Dense(10, activation='sigmoid'))

model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=0.1),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [11]:
model.fit(x_train, y_train, epochs=10, batch_size=32)

Train on 60000 samples
Epoch 1/10
60000/60000 [==============================] - 12s 195us/sample - loss: 1.1027 - accuracy: 0.6784
Epoch 2/10
60000/60000 [==============================] - 11s 180us/sample - loss: 0.3483 - accuracy: 0.9010
Epoch 3/10
60000/60000 [==============================] - 11s 176us/sample - loss: 0.2809 - accuracy: 0.9188
Epoch 4/10
60000/60000 [==============================] - 14s 227us/sample - loss: 0.2405 - accuracy: 0.9303
Epoch 5/10
60000/60000 [==============================] - 15s 249us/sample - loss: 0.2099 - accuracy: 0.9390
Epoch 6/10
60000/60000 [==============================] - 15s 248us/sample - loss: 0.1864 - accuracy: 0.9458
Epoch 7/10
60000/60000 [==============================] - 15s 249us/sample - loss: 0.1667 - accuracy: 0.9510
Epoch 8/10
60000/60000 [==============================] - 15s 250us/sample - loss: 0.1501 - accuracy: 0.9567
Epoch 9/10
60000/60000 [==============================] - 16s 260us/sample - loss: 0.1369 - accuracy: 0.9

In [12]:
model.evaluate(x_train,  y_train)

60000/1 [===============================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[0.11381090907379984, 0.9673333]